### ISSUE TITLE
Can't be installed on macOS

### ISSUE THREAD

**Issue by elsayed1** [CS-Eevee/react-proto#117]
### Details
- OS -> Montery 12.1

- “React-Proto” cannot be opened because the developer cannot be verified.

### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 5.4):
- Operating System and version (Mac or Linux):
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by juliomac** [comment]
Just go to Preferences -> Security...

There will be a warning on the Botton saying React Proto was Blocked. Click it and voila !
