### ISSUE TITLE
China can not download 

### ISSUE THREAD

**Issue by miyaliunian** [CS-Eevee/react-proto#92]
### Possible Fix

<details><summary>Additional Info</summary>

### Your Environment

- Environment name and version (e.g. Windows 10, node.js 5.4):
- Operating System and version (Mac or Linux):
- Useful link to screenshot or any other information:

### Steps to Reproduce

1.  first...
2.
3.
4.

### Stack Trace

</details>

**Comment by brianwtaylor** [comment]
Hi miyaliunian what OS were you using when you tried to use the tool?

**Comment by miyaliunian** [comment]
Mac OS  


> 在 2019年8月16日，上午12:47，Brian Taylor <notifications@github.com> 写道：
> 
> iyaliunian what OS were you using when you tried to use the tool?

**Comment by brianwtaylor** [comment]
my apologies if the tool is not working for you on macOS in China. I've downloaded the app on macOS today and the tool is working and functional. I will investigate this in the future as a new version is closer to release.

**Comment by cqh963852** [comment]
![image](https://user-images.githubusercontent.com/17702287/124360504-cbd88a00-dc5c-11eb-920a-e07c4b9b2d21.png)
Can I download  it manually？
